package ankit.com;

public class ExceptionExample {

	public static void main(String[] args) {
		try {
			System.out.println("Starting...");
			System.out.println("We have got two numbers");
			int n1 = 50;
			int n2 = 0;
			int result = n1/n2;
			System.out.println("division of :" +result);
		}
		catch(ArithmeticException e) {
			
			System.out.println(e.getMessage());
			System.out.println("n2 can not be zero");
			
		}
		catch(NumberFormatException e) {
			System.out.println("Invalid number :");
			System.out.println(e.getMessage());
		}
		catch(Exception e) {
			System.out.println("Error !!");
			System.out.println(e.getMessage());
		}
		System.out.println("Terminated...");
		
		

	}

}
